// client/src/app/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../service/auth.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {

  signUpForm = this.formBuilder.group({
    firstName: ['', Validators.required],
    lastName: ['', Validators.required],
    email: ['', Validators.compose([Validators.required, Validators.email])],
    phoneNumber: ['', Validators.required],
    username: ['', Validators.required],
    password: ['', Validators.required],
    passwordConfirmation: ['', Validators.required]
  });

  hide = true;

  constructor(
    private formBuilder: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) { }

  ngOnInit(): void {
  }

  signUp() {
    const result = this.authService.signUp(this.signUpForm.value).subscribe(
      res => console.log(res), error => console.log(error)
    );
  }
}

<div class="content-wrapper">
    <form [formGroup]="signUpForm" (ngSubmit)="signUp()">
        <h1>User Sign Pp</h1>

        <mat-form-field [style.width.px]=300 appearance="fill">
            <mat-label>First name</mat-label>
            <input matInput type="text" formControlName="firstName" required>
        </mat-form-field>
        <br />
        <mat-form-field [style.width.px]=300 appearance="fill">
            <mat-label>Last name</mat-label>
            <input matInput type="text" formControlName="lastName" required>
        </mat-form-field>
        <br />
        <mat-form-field [style.width.px]=300 appearance="fill">
            <mat-label>Email</mat-label>
            <input matInput type="email" formControlName="email" required>
        </mat-form-field>
        <br />
        <mat-form-field [style.width.px]=300 appearance="fill">
            <mat-label>Phone number</mat-label>
            <input matInput type="text" formControlName="phoneNumber" required>
        </mat-form-field>
        <br />
        <mat-form-field [style.width.px]=300 appearance="fill">
            <mat-label>Username</mat-label>
            <input matInput type="text" formControlName="username" required>
        </mat-form-field>
        <br />
        <mat-form-field [style.width.px]=300 appearance="fill">
            <mat-label>Password</mat-label>
            <input matInput [type]="hide ? 'password' : 'text'" formControlName="password" required>
            <button mat-icon-button matSuffix (click)="hide = !hide" [attr.aria-label]="'Hide password'" [attr.aria-pressed]="hide">
                <mat-icon>{{hide ? 'visibility_off' : 'visibility'}}</mat-icon>
            </button>
        </mat-form-field>
        <br />
        <mat-form-field [style.width.px]=300 appearance="fill">
            <mat-label>Password confirmation</mat-label>
            <input matInput [type]="hide ? 'password' : 'text'" formControlName="passwordConfirmation" required>
            <button mat-icon-button matSuffix (click)="hide = !hide" [attr.aria-label]="'Hide password'" [attr.aria-pressed]="hide">
                <mat-icon>{{hide ? 'visibility_off' : 'visibility'}}</mat-icon>
            </button>
        </mat-form-field>
        <br />

        <button mat-raised-button [style.width.px]=300 color="primary" type="submit" [disabled]="!signUpForm.valid">Sign up</button>
        
        <br />
        <br />
        <br />
        <p>Already resgistered?</p>
        
        <button mat-raised-button [style.width.px]=300 >Log in</button>
        
    </form>
</div>

// client-react/src/component/Signup.js
import React, { useState } from 'react'

import { makeStyles } from '@material-ui/core/styles';
import '../style/Login.css'

import FormControl from '@material-ui/core/FormControl'
import InputLabel from '@material-ui/core/InputLabel'
import OutlinedInput from '@material-ui/core/OutlinedInput'
import Visibility from '@material-ui/icons/Visibility'
import VisibilityOff from '@material-ui/icons/VisibilityOff'
import InputAdornment from '@material-ui/core/InputAdornment'
import IconButton from '@material-ui/core/IconButton'
import Button from '@material-ui/core/Button';

import { Link, useHistory } from 'react-router-dom';

import authService from '../service/AuthService'

const useStyles = makeStyles((theme) => ({
    root: {
      display: 'flex',
      flexWrap: 'wrap',
    },
    textField: {
        marginTop: theme.spacing(1),
        width: '30ch',
    },
    button: {
        width: '100%'
    }
  }));

export default function Signup() {

    const classes = useStyles();

    const history = useHistory();

    const [visibility, setVisibility] = useState(false)
    const [userInformation, setUserInformation] = useState({
        firstName: '',
        lastName: '',
        email: '',
        phoneNumber: '',
        username: '',
        password: '',
        passwordConfirmation: ''
    })

    const isFormValid = () => {
        return userInformation.firstName !== '' && userInformation.lastName !== '' && userInformation.email !== '' &&
                userInformation.phoneNumber !== '' && userInformation.username !== '' && userInformation.password !== '' &&
                userInformation.passwordConfirmation !== ''
    }

    const handleClickShowPassword = (event) => {
        event.preventDefault()
        setVisibility(!visibility)
    }

    const handleChange = (prop) => event => {
        setUserInformation({ ...userInformation, [prop]: event.target.value })
    }

    const handleClickSignUp = (event) => {
        event.preventDefault()
        authService
            .signUp(userInformation)
            .then(
                () => {
                    history.push("/login")
                },
                error => console.log(error)
            )
    }

    return(
        <div className="root">
            <form>
                <br />
                <h2>Registration page</h2>
                <FormControl variant="outlined" className={classes.textField}>
                    <InputLabel htmlFor="firstName">First name</InputLabel>
                    <OutlinedInput 
                        id="firstName"
                        type="text"
                        value={userInformation.firstName}
                        onChange={handleChange('firstName')}
                        labelWidth={70}
                    />
                </FormControl>
                <br />
                <FormControl variant="outlined" className={classes.textField}>
                    <InputLabel htmlFor="lastName">Last name</InputLabel>
                    <OutlinedInput 
                        id="lastName"
                        type="text"
                        value={userInformation.lastName}
                        onChange={handleChange('lastName')}
                        labelWidth={70}
                    />
                </FormControl>
                <br />
                <FormControl variant="outlined" className={classes.textField}>
                    <InputLabel htmlFor="email">Email</InputLabel>
                    <OutlinedInput 
                        id="email"
                        type="email"
                        value={userInformation.email}
                        onChange={handleChange('email')}
                        labelWidth={70}
                    />
                </FormControl>
                <br />
                <FormControl variant="outlined" className={classes.textField}>
                    <InputLabel htmlFor="phoneNumber">Phone number</InputLabel>
                    <OutlinedInput 
                        id="phoneNumber"
                        type="text"
                        value={userInformation.phoneNumber}
                        onChange={handleChange('phoneNumber')}
                        labelWidth={70}
                    />
                </FormControl>
                <br />
                <FormControl variant="outlined" className={classes.textField}>
                    <InputLabel htmlFor="username">Username</InputLabel>
                    <OutlinedInput 
                        id="username"
                        type="text"
                        value={userInformation.username}
                        onChange={handleChange('username')}
                        labelWidth={70}
                    />
                </FormControl>
                <br />
                <FormControl variant="outlined" className={classes.textField}>
                    <InputLabel htmlFor="password">Password</InputLabel>
                    <OutlinedInput
                        id="password"
                        type={visibility ? 'text' : 'password'}
                        value={userInformation.password}
                        onChange={handleChange('password')}
                        endAdornment={
                        <InputAdornment position="end">
                            <IconButton
                            aria-label="toggle password visibility"
                            onClick={handleClickShowPassword}
                            edge="end"
                            >
                            {visibility ? <Visibility /> : <VisibilityOff />}
                            </IconButton>
                        </InputAdornment>
                        }
                        labelWidth={70}
                    />
                </FormControl>
                <br />
                <FormControl variant="outlined" className={classes.textField}>
                    <InputLabel htmlFor="passwordConfirmation">Password confirmation</InputLabel>
                    <OutlinedInput
                        id="passwordConfirmation"
                        type={visibility ? 'text' : 'password'}
                        value={userInformation.passwordConfirmation}
                        onChange={handleChange('passwordConfirmation')}
                        endAdornment={
                        <InputAdornment position="end">
                            <IconButton
                            aria-label="toggle password visibility"
                            onClick={handleClickShowPassword}
                            edge="end"
                            >
                            {visibility ? <Visibility /> : <VisibilityOff />}
                            </IconButton>
                        </InputAdornment>
                        }
                        labelWidth={70}
                    />
                </FormControl>
                <br />
                <br />
                <Button variant="contained" color="primary" className={classes.button} onClick={handleClickSignUp} disabled={!isFormValid()}>
                    Register
                </Button>
                <br />
                <br />
                <p>Already signed up?</p>
                <Link to="/login">
                    <Button variant="outlined" color="primary" className={classes.button}>
                        Login
                    </Button>
                </Link>      
            </form>
        </div>
    )
}
